In [1]:
!nvidia-smi

Thu May 22 17:00:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P8              5W /   35W |     980MiB /   4096MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
torch.__version__

'2.6.0+cu126'

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
scalar=torch.tensor(7)  #a scalar tensor with one component and no basis vectors
scalar

tensor(7)

In [7]:
print(scalar.ndim)
scalar.item()

0


7

In [12]:
vector=torch.tensor([7,3])
print(vector , vector.ndim , vector.shape)

tensor([7, 3]) 1 torch.Size([2])


In [13]:
matrix=torch.tensor([[7,3],[4,5]])
print(matrix , matrix.ndim , matrix.shape)

tensor([[7, 3],
        [4, 5]]) 2 torch.Size([2, 2])


In [15]:
matrix[1] , matrix[0] , matrix[1][1]

(tensor([4, 5]), tensor([7, 3]), tensor(5))

In [ ]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR,  TENSOR.ndim,  TENSOR.shape            #basically this tensor is only one frame of the 3d tensor - 1D 3x3 face

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
random_tensor=torch.rand(3,4,2)    #3,4,2 is the shape or size of the tensor
random_tensor,  random_tensor.ndim                #3 faces of 4x2 shape - 3 faces like a 3x3 rubics cube

(tensor([[[0.0441, 0.4812],
          [0.7921, 0.7487],
          [0.8678, 0.7611],
          [0.7052, 0.9695]],
 
         [[0.3855, 0.1978],
          [0.3241, 0.7754],
          [0.8880, 0.7347],
          [0.3450, 0.3249]],
 
         [[0.2202, 0.9417],
          [0.0558, 0.6707],
          [0.3088, 0.4064],
          [0.4950, 0.9105]]]),
 3)

In [ ]:
random_img_size_tensor=torch.rand(224,224,3) #3 color channels  - 224 faces of 224x3 matrices
random_img_size_tensor.ndim

3

In [4]:
zero_tensor=torch.zeros(size=(2,3))
one_tensor=torch.ones(2,3)
zero_tensor , one_tensor , one_tensor.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [9]:
x=torch.arange(0,5)
torch.arange(start=1, end=100, step=17) , x

(tensor([ 1, 18, 35, 52, 69, 86]), tensor([0, 1, 2, 3, 4]))

In [ ]:
tensor_like=torch.zeros_like(input=x)  #inherits the shape of the input tensor
tensor_like

tensor([0, 0, 0, 0, 0])

In [14]:
torch.rand(size=(3,3), dtype=torch.float16, requires_grad=None)

tensor([[0.9614, 0.8760, 0.5283],
        [0.7026, 0.0020, 0.9995],
        [0.7842, 0.6040, 0.6948]], dtype=torch.float16)

In [19]:
t=torch.rand(3,4)
print(t)
torch.min(t), torch.max(t), torch.mean(t), torch.sum(t)

tensor([[0.1402, 0.6433, 0.8564, 0.9427],
        [0.1691, 0.0544, 0.3831, 0.8644],
        [0.9916, 0.3382, 0.0357, 0.1307]])


(tensor(0.0357), tensor(0.9916), tensor(0.4625), tensor(5.5499))

In [25]:
t.argmin(), t.argmax()  #find the index value or position within the tensor with min or max value

(tensor(10), tensor(8))

In [6]:
x=torch.arange(1,10)
print(f"\n{x}")
print(f"\n{x.shape}")
z=x.reshape(3,3)
print(f"\n{z, x}")
y=x.view(3,3)
print(f"\n{y, x}")



tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.Size([9])

(tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

(tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))


In [15]:
x_stacked=torch.stack([x, x], dim=0)
x_stacked , torch.vstack([x,x]) , torch.hstack([x,x])

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [31]:
x=torch.rand(size=(1,2,3))
print(f"\n{x, x.shape}")
print(f"\n{x.squeeze().shape , x.squeeze()}")
print(f"\n{x.unsqueeze(dim=0).shape , x.unsqueeze(dim=0)}")


(tensor([[[0.8190, 0.2742, 0.5222],
         [0.0154, 0.2854, 0.2613]]]), torch.Size([1, 2, 3]))

(torch.Size([2, 3]), tensor([[0.8190, 0.2742, 0.5222],
        [0.0154, 0.2854, 0.2613]]))

(torch.Size([1, 1, 2, 3]), tensor([[[[0.8190, 0.2742, 0.5222],
          [0.0154, 0.2854, 0.2613]]]]))


In [33]:
m=torch.rand(size=(224,224,3))
m_permuted=m.permute(2, 0, 1)
print(f"{m_permuted.shape}")

torch.Size([3, 224, 224])


In [44]:
m[221,223,1] , m[0,1,:]

(tensor(0.8513), tensor([0.1614, 0.2716, 0.7782]))

In [50]:
array=np.array([1.0,3.0,7.0])
tensor=torch.from_numpy(array)
array , tensor

(array([1., 3., 7.]), tensor([1., 3., 7.], dtype=torch.float64))

In [51]:
t=torch.tensor([4,6,8])
n_array=t.numpy()
t , n_array

(tensor([4, 6, 8]), array([4, 6, 8]))

In [53]:
RANDOM_SEED=77
torch.manual_seed(RANDOM_SEED)
t1=torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
t2=torch.rand(3,3)
t1==t2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [54]:
torch.cuda.device_count()

1

In [55]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [57]:
t=torch.tensor([1,2,3]).to(device)
t

tensor([1, 2, 3], device='cuda:0')

In [59]:
t=t.cpu()
t.device

device(type='cpu')