In [1]:
!nvidia-smi

Thu May 22 17:00:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P8              5W /   35W |     980MiB /   4096MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.__version__

'2.6.0+cu126'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
scalar=torch.tensor(7)  #a scalar tensor with one component and no basis vectors
scalar

tensor(7)

In [7]:
print(scalar.ndim)
scalar.item()

0


7

In [12]:
vector=torch.tensor([7,3])
print(vector , vector.ndim , vector.shape)

tensor([7, 3]) 1 torch.Size([2])


In [13]:
matrix=torch.tensor([[7,3],[4,5]])
print(matrix , matrix.ndim , matrix.shape)

tensor([[7, 3],
        [4, 5]]) 2 torch.Size([2, 2])


In [15]:
matrix[1] , matrix[0] , matrix[1][1]

(tensor([4, 5]), tensor([7, 3]), tensor(5))

In [ ]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR,  TENSOR.ndim,  TENSOR.shape            #basically this tensor is only one frame of the 3d tensor - 1D 3x3 face

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
random_tensor=torch.rand(3,4,2)    #3,4,2 is the shape or size of the tensor
random_tensor,  random_tensor.ndim                #3 faces of 4x2 shape - 3 faces like a 3x3 rubics cube

(tensor([[[0.0441, 0.4812],
          [0.7921, 0.7487],
          [0.8678, 0.7611],
          [0.7052, 0.9695]],
 
         [[0.3855, 0.1978],
          [0.3241, 0.7754],
          [0.8880, 0.7347],
          [0.3450, 0.3249]],
 
         [[0.2202, 0.9417],
          [0.0558, 0.6707],
          [0.3088, 0.4064],
          [0.4950, 0.9105]]]),
 3)

In [ ]:
random_img_size_tensor=torch.rand(224,224,3) #3 color channels  - 224 faces of 224x3 matrices
random_img_size_tensor.ndim

3